[workspace]
name = "rustformer"
version = "0.1.0"
edition = "2021"
members = ["micrograd", "nn", "transformer", "demo", "interfaces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
