[package]
name = "micrograd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix_library = { path = "../../matrix_library" }
serde = { version = "1.0.203", features = ["derive", "rc"] }
